config/routes.rb
Rails.application.routes.draw do
  root "tweegeonctlr#index"
  get "tweegeonctlr/index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweegeonctlr_controller.rb
class TweegeonctlrController < ApplicationController
	def index
		flag = 1
		username = params[:user][:name] rescue nil
		puts username
		if username.to_s != ''
			client = Twitter::REST::Client.new do |config|
				config.consumer_key        = "your consumer key"
				config.consumer_secret     = "your consumer secret"
				config.access_token        = "your access token"
				config.access_token_secret = "your access token secret"
			end
			begin
				user_obj = client.user(username)
			rescue => e
				puts "****************Error occured***************"
				puts "#{e}"
				puts "**************************************************"
				@response = e
				flag = 0
			end
			if flag == 1
				if username.eql?(user_obj.screen_name)
					@tweets = client.user_timeline(username)
				else
					if username.eql?(user_obj.name)
						@tweets = client.user_timeline(username)
					end
				end
			else
				@tweets = ''
			end
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweegeonctlr_helper.rb
module TweegeonctlrHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweegeon-It fetches any User's public tweets</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweegeonctlr/index.html.erb
<header>
	<div class="header-wrapper container-fluid">
		<h1 class="text-center"><a href="https://tweegeon.herokuapp.com">TWEEGEON</a></h1>
	</div>
</header>
<div class="container-fluid">
	<div class="input-container txt-center container-fluid">
		<%= form_tag(tweegeonctlr_index_path, method: "get") do %>
			<span class="col-md-1"></span>
			<span class="col-md-3 col-sm-4 col-xs-12 text-center"><%= label_tag("Enter Twitter Username :") %></span>
			<span class="col-md-4 col-sm-4 col-xs-12 text-center"><%= text_field "user", "name", :class=>'txt-box', :autofocus=>true %></span>
			<span class="col-md-3 col-sm-3 col-xs-12 text-center"><%= submit_tag("Get Tweets",:class=>'btn',:id=>'sub') %></span>			 
			<span class="col-md-1"></span>
		<% end %>
	</div>
	<%if @tweets.to_s != '' %>
		<ul class="tweets-container container-fluid ">
			<% @tweets.each do |tweet| %>
				<li class="tweet col-md-12 col-sm-12 col-xs-12"><%= image_tag(tweet.user.profile_image_url)%><span class="tweet-data"><%= label_tag(tweet.text) %><%= link_to tweet.user.screen_name , "https://www.twitter.com/#{tweet.user.screen_name}" %></span>
				</li>
			<% end %>
		</ul>
	<% else %>
		<h3 class="txt-center wn col-md-12 col-sm-12 col-xs-12">Welcome to Tweegeon. Please enter any twitter username to retrieve recent tweets</h3>
		<% if @response != '' %>
			<h3 class="txt-center warning col-md-12 col-sm-12 col-xs-12"><%= @response %></h3>
		<% end %>
	<% end %>
<footer>
	<div class="container-fluid footer-wrapper text-center">
		<p>This Site is developed by <a href="https://github.com/rtvalluri">Raviteja Valluri</a></p>
	</div>
</footer>
</div>